version: "3"

services:
  # consul
  test_consul_server:
    image: consul
    restart: always
    container_name: test_consul_server
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    ports:
      - "8500:8500"
    command: agent -server -bootstrap-expect=1 -ui -node=test_consul_server -client=0.0.0.0 -datacenter=consul-shenzhen

  apollo-db:
    container_name: apollo-db
    image: nacos/nacos-mysql:5.7
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=nacos_devtest
      - MYSQL_USER=nacos
      - MYSQL_PASSWORD=nacos
    volumes:
    - ./initsql/apolloconfigdb.sql:/docker-entrypoint-initdb.d/apolloconfigdb.sql
    - ./initsql/apolloportaldb.sql:/docker-entrypoint-initdb.d/apolloportaldb.sql
    ports:
      - "3306:3306"

  # apollo
  test_apollo_server:
    image: nobodyiam/apollo-quick-start
    container_name: test_apollo_server
    depends_on:
      - apollo-db
    ports:
      - "8080:8080"
      - "8070:8070"
    links:
      - apollo-db

  # nacos
  test_nacos_server:
    image: nacos/nacos-server:latest
    container_name: test_nacos_server
    restart: on-failure
    environment:
    - PREFER_HOST_MODE=hostname
    - MODE=standalone
    - SPRING_DATASOURCE_PLATFORM=mysql
    - MYSQL_SERVICE_HOST=apollo-db
    - MYSQL_SERVICE_DB_NAME=nacos_devtest
    - MYSQL_SERVICE_PORT=3306
    - MYSQL_SERVICE_USER=nacos
    - MYSQL_SERVICE_PASSWORD=nacos
    ports:
      - "8848:8848"
      - "9555:9555"
    depends_on:
      - apollo-db
    volumes:
    - ./nacos-custom.properties:/home/nacos/init.d/custom.properties


  test_etcd_server:
    image: quay.io/coreos/etcd
    container_name: test_etcd_server
    command: etcd -name test_etcd_server -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379 -listen-peer-urls http://0.0.0.0:2380 -initial-cluster-token etcd-cluster -initial-cluster-state new
    ports:
    - "2379:2379"
    - "2380:2380"

