version: "3"

services:
  # consul
  test_consul_server:
    image: consul
    restart: always
    container_name: test_consul_server_0
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    ports:
      - "8500:8500"
    command: agent -server -bootstrap-expect=1 -ui -node=test_consul_server_0 -client=0.0.0.0 -datacenter=consul-shenzhen

  # nacos
  test_nacos_server:
    image: nacos/nacos-server:latest
    container_name: nacos-standalone-mysql
    environment:
    - PREFER_HOST_MODE=hostname
    - MODE=standalone
    - SPRING_DATASOURCE_PLATFORM=mysql
    - MYSQL_SERVICE_HOST=test_mysql_server
    - MYSQL_SERVICE_DB_NAME=nacos_devtest
    - MYSQL_SERVICE_PORT=3306
    - MYSQL_SERVICE_USER=nacos
    - MYSQL_SERVICE_PASSWORD=nacos
    ports:
      - "8848:8848"
      - "9555:9555"
    depends_on:
      - test_mysql_server
    restart: on-failure

  test_mysql_server:
    container_name: test_mysql_server
    image: nacos/nacos-mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=nacos_devtest
    - MYSQL_USER=nacos
    - MYSQL_PASSWORD=nacos
    ports:
      - "3306:3306"

  test_etcd_server:
    image: quay.io/coreos/etcd
    container_name: test_etcd_server
    command: etcd -name test_etcd_server -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379 -listen-peer-urls http://0.0.0.0:2380 -initial-cluster-token etcd-cluster -initial-cluster "etcd1=http://test_etcd_server:2380" -initial-cluster-state new
    ports:
    - "2379:2379"
    - "2380:2380"