version: "3"

services:
  consul_demo_server_0:
    image: consul
    restart: always
    container_name: consul_demo_server_0
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    ports:
    - 8500:8500
    command: agent -server -bootstrap-expect=1 -ui -node=consul_demo_server_0 -client=0.0.0.0 -datacenter=consul-shenzhen